# Generated by Django 6.0.1 on 2026-02-07 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('annee_scolaire', models.CharField(max_length=20, unique=True)),
                ('filieres', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('num_matricule', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_etudiant.annee')),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_etudiant.annee')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('note', models.FloatField()),
                ('enseignement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_etudiant.enseignement')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_etudiant.etudiant')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion_etudiant.semestre')),
            ],
            options={
                'unique_together': {('etudiant', 'enseignement', 'semestre')},
            },
        ),
    ]
